# Generated by Django 6.0.8 on 2026-09-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("timezone", models.CharField(max_length=100)),
                ("has_channels", models.BooleanField(default=False)),
                ("channel_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "countries",
                "ordering": ("country_code",),
            },
        ),
    ]
