# Generated by Django 6.0.8 on 2026-09-07 12:56

import django.db.models.deletion
import src.apps.channels.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("countries", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                (
                    "urls",
                    models.JSONField(default=src.apps.channels.models.default_urls),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channels",
                        to="categories.category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channels",
                        to="countries.country",
                    ),
                ),
            ],
            options={
                "db_table": "channels",
                "ordering": ("name", "id"),
            },
        ),
    ]
