class ErrorCodes:
    # ========== AUTHENTICATION ERRORS ==========
    UNAUTHENTICATED = "UNAUTHENTICATED"

    # ========== AUTHORIZATION ERRORS ==========
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # ========== REPOSITORY ERRORS ==========
    NO_CHANGES_ERROR = "NO_CHANGES_ERROR"
    INVALID_FIELD_ERROR = "INVALID_FIELD_ERROR"

    NOT_FOUND = "NOT_FOUND"
    COUNTRY_NOT_FOUND = "COUNTRY_NOT_FOUND"
    CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND"
    URL_NOT_FOUND = "URL_NOT_FOUND"

    DUPLICATE_COUNTRY = "DUPLICATE_COUNTRY"
    DUPLICATE_CHANNEL = "DUPLICATE_CHANNEL"
    DUPLICATE_URL = "DUPLICATE_URL"

    # ========== SERVER ERRORS ==========
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    CACHE_ERROR = "CACHE_ERROR"

    # ========== VALIDATION ERRORS ==========
    VALIDATION_ERROR = "VALIDATION_ERROR"
