# Generated by Django 6.0.8 on 2026-09-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("id",), "verbose_name_plural": "Categories"},
        ),
    ]
